services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www/html
    entrypoint: >
      bash -c "chown -R www-data:www-data storage bootstrap/cache &&
              php-fpm"

  web:
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
