services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod

  web:
    environment:
      - VIRTUAL_HOST=enroll.bitgraft.dev
      - LETSENCRYPT_HOST=enroll.bitgraft.dev
      - LETSENCRYPT_EMAIL=ismael.guajardo.dev@gmail.com
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    networks:
      - laravel
      - web

networks:
  laravel:
  web:
    external: true
